### ISSUE TITLE
Katakana misspelling of “Transformer”

### ISSUE THREAD

**Issue by Vivit-R** [greghendershott/fear-of-macros#38]
Section 3.1's amusing pop culture reference to the _Transformers_ media franchise and its Japanese roots transliterates “Transformer” as トランスフォーマ _(toransufōma),_ converting the “-er” into a short /a/ when it should be a long /aː/ _(toransufōmā)._ The correct spelling has an additional ー on the end: トランスフォーマー.

**Comment by naoyafurudono** [comment]
Hi, I am native Japanese and think both トランスフォーマー and トランスフォーマ are okay, while many normal native Japanese tend to write トランスフォーマー.

On the other hand, Japanese engineers and programmers tend to eliminate ー at the end word, i.e., write トランスフォーマ, since ー confuse us with hyphen, 一 (a Chinese character denotes 1), and so on.

I feel both are natural, but prefer トランスフォーマ  in fear of macros.

**Comment by Vivit-R** [comment]
TIL! Very interesting, thank you.

**Comment by greghendershott** [comment]
Thank you for the feedback.

I had glanced at this when I was busy, and thought probably it wasn't an urgent to-do --- but I didn't mean to neglect it so long. 

In closing I will leave you material for a possible fresh issue by saying "sumimasen!". :)
